language: java

addons:
  sonarcloud:
    organization: "benjamincinquincpe" 
    token:
      secure: $SONAR_TOKEN

services:
  - docker

cache:
  directories:
    - "$HOME/.m2/repository"

jobs:
  include:
    - stage: build
      script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -Dsonar.projectKey=benjamincinquincpe_sample-application-students
    - stage: deploy
      script: 
        - docker build -t "$DOCKER_USERNAME"/my-sample-app-changelog sample-application-db-changelog-job/
        - docker tag "$DOCKER_USERNAME"/my-sample-app-changelog "$DOCKER_USERNAME"/my-sample-app-changelog:develop
        - docker push "$DOCKER_USERNAME"/my-sample-app-changelog:develop 
        - docker build -t "$DOCKER_USERNAME"/my-sample-app-api sample-application-http-api-server/
        - docker tag "$DOCKER_USERNAME"/my-sample-app-api "$DOCKER_USERNAME"/my-sample-app-api:develop
        - docker push "$DOCKER_USERNAME"/my-sample-app-api:develop
