language: java

addons:
  sonarcloud:
    organization: "benjamincinquincpe" 
    token:
      secure: $SONAR_TOKEN

services:
  - docker

cache:
  directories:
    - "$HOME/.m2/repository"

jobs:
  include:
    - stage: build
      script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -Dsonar.projectKey=benjamincinquincpe_sample-application-students
    - stage: deploy
      script: bash docker_push
