language: java

addons:
  sonarcloud:
    organization: "benjamincinquincpe" # the key of the org you chose at step #3

services:
  - docker

script:
  - mvn dependency:go-offline clean verify

cache:
  directories:
    - "$HOME/.m2/repository"

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: develop
